### ISSUE TITLE
Exception trying to inject Big Buck Arcade

### ISSUE THREAD

**Issue by Nitch2024** [EquiFox/MInjector#4]
"System.BadImageFormatException: Could not load file or assembly 'MInject, Version=1.0.6540.41846, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'MInject, Version=1.0.6540.41846, Culture=neutral, PublicKeyToken=null'
   at MInjector.MonoInjector.Inject(Process p_TargetProcess, Settings p_InjectionSettings)
   at MInjector.Main.injectBtn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

Process: Buck.exe
Assembly: C:\Games\Big Buck Hunter Arcade\Buck_Data\Managed\Assembly-CSharp.dll
Namespace: Assembly-CSharp
Class: PlayerReticleController
Method: UpdateReticlePosition

**Comment by Nitch2024** [comment]
Ok found the issues. We can close this ticket

1. For some reason the x86 Minject.dll assembly was used instead of the x64
2. I did not need a namespace

Process: Buck.exe
Assembly: C:\Games\Big Buck Hunter Arcade\Buck_Data\Managed\Assembly-CSharp.dll
Namespace: [NONE LEFT EMPTY]
Class: PlayerReticleController
Method: UpdateReticlePosition
